# Generated by Django 5.2.4 on 2025-07-09 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('archivo', models.FileField(upload_to='videos_demo/')),
                ('creado', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
