# Generated by Django 5.2.4 on 2025-07-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='demovideo',
            options={'ordering': ['-creado'], 'verbose_name': 'Demo de vídeo', 'verbose_name_plural': 'Demos de vídeo'},
        ),
        migrations.AlterField(
            model_name='demovideo',
            name='archivo',
            field=models.FileField(upload_to='videos_demo/', verbose_name='Archivo de vídeo'),
        ),
        migrations.AlterField(
            model_name='demovideo',
            name='creado',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Fecha de subida'),
        ),
        migrations.AlterField(
            model_name='demovideo',
            name='descripcion',
            field=models.TextField(blank=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='demovideo',
            name='titulo',
            field=models.CharField(max_length=100, verbose_name='Título'),
        ),
    ]
