# Generated by Django 5.2.4 on 2025-07-22 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IAGeneratedResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servicio', models.CharField(max_length=100, verbose_name='Servicio')),
                ('usuario', models.CharField(default='anónimo', max_length=100, verbose_name='Nombre de usuario')),
                ('entrada_usuario', models.TextField(verbose_name='Entrada del usuario')),
                ('resultado_ia', models.TextField(verbose_name='Respuesta generada por IA')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
            ],
            options={
                'verbose_name': 'Respuesta generada por IA',
                'verbose_name_plural': 'Respuestas generadas por IA',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
