# Generated by Django 5.2.4 on 2026-04-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriprompt_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='iageneratedresponse',
            name='html_file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Archivo HTML'),
        ),
        migrations.AddField(
            model_name='iageneratedresponse',
            name='paciente',
            field=models.CharField(default='desconocido', max_length=100, verbose_name='Paciente'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iageneratedresponse',
            name='pdf_file',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Archivo PDF'),
        ),
    ]
