# Generated by Django 5.2.4 on 2026-05-05 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriprompt_app', '0002_iageneratedresponse_html_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iageneratedresponse',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True, verbose_name='Última actualización'),
        ),
        migrations.AddField(
            model_name='iageneratedresponse',
            name='source_type',
            field=models.CharField(choices=[('fallback', 'Fallback estructurado'), ('openai', 'IA · OpenAI'), ('gemini', 'IA · Gemini'), ('mock', 'Modo demo'), ('manual', 'Manual')], db_index=True, default='fallback', max_length=50, verbose_name='Fuente de generación'),
        ),
        migrations.AlterField(
            model_name='iageneratedresponse',
            name='entrada_usuario',
            field=models.TextField(help_text='Datos estructurados introducidos en el formulario.', verbose_name='Entrada del usuario'),
        ),
        migrations.AlterField(
            model_name='iageneratedresponse',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación'),
        ),
        migrations.AlterField(
            model_name='iageneratedresponse',
            name='paciente',
            field=models.CharField(max_length=100, verbose_name='Paciente / cliente'),
        ),
        migrations.AlterField(
            model_name='iageneratedresponse',
            name='resultado_ia',
            field=models.TextField(help_text='Respuesta generada en formato JSON serializado.', verbose_name='Resultado generado'),
        ),
        migrations.AlterField(
            model_name='iageneratedresponse',
            name='servicio',
            field=models.CharField(default='NutriPrompt', max_length=100, verbose_name='Servicio'),
        ),
        migrations.AlterField(
            model_name='iageneratedresponse',
            name='usuario',
            field=models.CharField(default='Bea', max_length=100, verbose_name='Usuario'),
        ),
        migrations.AddIndex(
            model_name='iageneratedresponse',
            index=models.Index(fields=['servicio', 'fecha_creacion'], name='nutriprompt_servici_7cc493_idx'),
        ),
        migrations.AddIndex(
            model_name='iageneratedresponse',
            index=models.Index(fields=['paciente', 'fecha_creacion'], name='nutriprompt_pacient_b0e296_idx'),
        ),
        migrations.AddIndex(
            model_name='iageneratedresponse',
            index=models.Index(fields=['source_type', 'fecha_creacion'], name='nutriprompt_source__86d542_idx'),
        ),
    ]
