# Generated by Django 5.2.4 on 2026-06-08 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nutriprompt_app', '0003_iageneratedresponse_fecha_actualizacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iageneratedresponse',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='iageneratedresponse',
            name='fecha_creacion',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='iageneratedresponse',
            name='html_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='iageneratedresponse',
            name='pdf_file',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='iageneratedresponse',
            name='servicio',
            field=models.CharField(default='NutriPrompt', max_length=100),
        ),
        migrations.AlterField(
            model_name='iageneratedresponse',
            name='source_type',
            field=models.CharField(choices=[('fallback', 'Motor nutricional estructurado'), ('openai', 'IA · OpenAI'), ('gemini', 'IA · Gemini'), ('mock', 'Modo demo'), ('manual', 'Manual')], db_index=True, default='fallback', max_length=50, verbose_name='Fuente de generación'),
        ),
        migrations.AlterField(
            model_name='iageneratedresponse',
            name='usuario',
            field=models.CharField(default='Bea', max_length=100),
        ),
        migrations.CreateModel(
            name='SmartIntakeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intake_type', models.CharField(choices=[('nutrition_pdf', 'PDF de nutricionista / pauta nutricional'), ('product_label', 'Producto o etiqueta'), ('pantry_image', 'Foto de despensa'), ('fridge_image', 'Foto de nevera'), ('ingredient_image', 'Ingrediente concreto')], db_index=True, max_length=40, verbose_name='Tipo de entrada')),
                ('original_file', models.FileField(upload_to='vision/uploads/', verbose_name='Archivo original')),
                ('extracted_text', models.TextField(blank=True, verbose_name='Texto extraído')),
                ('detected_items', models.JSONField(blank=True, default=list, verbose_name='Elementos detectados')),
                ('detected_restrictions', models.JSONField(blank=True, default=list, verbose_name='Restricciones detectadas')),
                ('detected_warnings', models.JSONField(blank=True, default=list, verbose_name='Alertas detectadas')),
                ('structured_summary', models.JSONField(blank=True, default=dict, verbose_name='Resumen estructurado')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('processed', 'Procesado'), ('failed', 'Fallido')], db_index=True, default='pending', max_length=20, verbose_name='Estado')),
                ('error_message', models.TextField(blank=True, verbose_name='Mensaje de error')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Fecha de creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
            ],
            options={
                'verbose_name': 'Análisis Smart Intake',
                'verbose_name_plural': 'Análisis Smart Intake',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['intake_type', 'created_at'], name='nutriprompt_intake__042c5e_idx'), models.Index(fields=['status', 'created_at'], name='nutriprompt_status_09d90e_idx')],
            },
        ),
    ]
